### ISSUE TITLE
本地环境正常，docker 环境下报错，Plugin [elasticsearch-analysis-ik-8.8.2] is missing a descriptor properties file

### ISSUE THREAD

**Issue by shimanongfu** [infinilabs/analysis-ik#1011]
本地环境与docker image都是8.8.2，本地环境可正常加载ik插件，docker下报错。

**Comment by zupermanOK** [comment]
![image](https://github.com/medcl/elasticsearch-analysis-ik/assets/32672783/6c5de490-3f9b-45fd-a69a-701c16d86c12)
是不是没有创建文件夹

**Comment by wuwenbao** [comment]
加入 -b 参数试试
`bin/elasticsearch-plugin install -b`

**Comment by xiunchen** [comment]
./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.8.2/elasticsearch-analysis-ik-8.8.2.zip

用这个方式安装

**Comment by sincebyte** [comment]
hi guys？ 有解决方案了？

**Comment by sincebyte** [comment]
> ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.8.2/elasticsearch-analysis-ik-8.8.2.zip
> 
> 用这个方式安装

do not work

**Comment by sincebyte** [comment]
> 加入 -b 参数试试 `bin/elasticsearch-plugin install -b`

sorry , it do not work

**Comment by sincebyte** [comment]
> ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.8.2/elasticsearch-analysis-ik-8.8.2.zip
> 
> 用这个方式安装

sorry , do not work neither

**Comment by mingchiuli** [comment]
插件文件夹权限问题chomd 755 * -R

**Comment by skyliwq** [comment]
同样问题 有解决的方法吗

**Comment by zyqwst** [comment]
同样的问题，作者能帮忙看看啥原因吗？
ES镜像版本：docker.elastic.co/elasticsearch/elasticsearch:8.11.3
IK分词器版本：elasticsearch-analysis-ik-8.11.3.zip
docker-compose如下：
```
version: '3.1'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ./elasticsearch-analysis-ik-8.11.3.zip:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-8.11.3.zip
      - ./data:/usr/share/elasticsearch/data 
      - ./logs:/usr/share/elasticsearch/logs
    # command: >
    #   bash -c '
    #     elasticsearch-plugin install -b file:///usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-8.11.3.zip && exec /usr/local/bin/docker-entrypoint.sh
    #   '
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ES_PORT}:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./kibanadata:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - I18N_LOCALE=zh-CN
    ports:
      - ${KIBANA_PORT}:5601
```
报错如下图
![image](https://github.com/medcl/elasticsearch-analysis-ik/assets/10893736/0d797d13-09e5-47f7-af05-9d1904f88741)
